import Head from 'next/head'
import Plus from '../components/icons/Plus'
import NavBar from '../components/NavBar'
import ProductCard from '../components/ProductCard'
import styleCard from '../components/ProductCard/ProductCard.module.css'

export default function Home() {
  return (
    <main style={{ width: '70vw', height: '100vh', margin: 'auto' }}>
      <Head>
        <title>Home - Titi Bakery</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <NavBar />
      <section>
        <ProductCard />
        <button
          className={styleCard.add}
          style={{
            width: '50px',
            height: '50px',
            position: 'fixed',
            right: 70
          }}
        >
          <Plus />
        </button>
      </section>
    </main>
  )
}
